### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by alphapapa** [shingo256/trashed#1]
Hi,

Great work converting to use `tabulated-list-mode`!

Here's some code you might want to use that simplifies the implementation of `trashed-read-files` a bit.  I think it makes it easier to understand.

```el
(defun trashed-read-files ()
  (let* ((files (directory-files-and-attributes trashed-files-dir nil nil t))
         (entries (cl-loop for (name . attrs) in files
                           unless (or (string= name ".") (string= name ".."))
                           collect (trashed-file-info name attrs))))
    (setf tabulated-list-entries entries)))

(defun trashed-file-info (name attrs)
  "Return list of name and vector for `tabulated-list-entries' for file NAME with ATTRS."
  (-let* ((type (cl-typecase (file-attribute-type attrs)
                  (string "l")
                  (null "-")
                  (t "d")))
          (size (number-to-string (file-attribute-size attrs)))
          (info-file (expand-file-name (concat name ".trashinfo") trashed-info-dir))
          ((path deletion-ts) (trashed-trashinfo info-file))
          (path (-> path url-unhex-string
                    (decode-coding-string 'utf-8 t)
                    (propertize 'mouse-face 'highlight)))
          (deletion-ts (format-time-string "%Y-%m-%d %H:%M:%S" deletion-ts)))
    (list name (vector type size deletion-ts path))))

(defun trashed-trashinfo (trashinfo-file)
  "Return list of original file path and deletion timestamp for TRASHINFO-FILE."
  (when (file-readable-p trashinfo-file)
    (with-temp-buffer
      (insert-file-contents trashinfo-file)
      (let* ((path (when (re-search-forward (rx bol "Path"
                                                (0+ blank) "=" (0+ blank)
                                                (group (1+ nonl))) nil t)
                     (match-string 1)))
             (deletion-ts (progn
                            (goto-char (point-min))
                            (when (re-search-forward (rx bol "DeletionDate"
                                                         (0+ blank) "=" (0+ blank)
                                                         (group (1+ nonl))) nil t)
                              (parse-iso8601-time-string (match-string 1))))))
        (list path deletion-ts)))))
```
Also, in the header, it says `Data & Time` instead of `Date & Time`.  You might want to use something more explicit like `Deleted At`.

BTW, you might find this interesting.  :)  https://github.com/alphapapa/rubbish.py

**Comment by shingo256** [comment]
Thank you for your suggestion and bug reports.  After quickly fixing the two issues in my code, I am trying to adopt the suggested code by testing it.  However it looks like there is an issue in my environment, where I have some trash files with wrong names (XXX.trashinfo which is the same as info file) due to a bug in Emacs(26.3) build-in file trashing process in `move-file-to-trash'.  Probably we need to add some codes to take care of some irregular cases, so let me investigate it.

Also, I am hesitating to use file-attribute-xxx as they require Emacs ver >=26.1 which I think is too new for those who have difficulty in updating their Emacs, like companies' shared environment, etc.

WIll keep you updated.

**Comment by alphapapa** [comment]
> However it looks like there is an issue in my environment, where I have some trash files with wrong names (XXX.trashinfo which is the same as info file) due to a bug in Emacs(26.3) build-in file trashing process in `move-file-to-trash'. Probably we need to add some codes to take care of some irregular cases, so let me investigate it.

If you find a bug in Emacs's `move-file-to-trash`, please do report the bug.  And please let me know if you can confirm that.

> Also, I am hesitating to use file-attribute-xxx as they require Emacs ver >=26.1 which I think is too new for those who have difficulty in updating their Emacs, like companies' shared environment, etc.

Understandable, but you might consider just supporting Emacs 26.1 or later.  It's already over a year old.  And using the `file-attribute-` accessors helps future-proof your code and makes it much easier to read.  Everyone will upgrade their Emacs eventually, and it will be harder to drop support for old versions later than to just support newer ones now.

**Comment by shingo256** [comment]
I sent a bug report, bug#37922.  Also, identified the issue in your code.  When it cannot find the corresponding info file, both `path` and `deletion-ts` are set to nil in `trashed-file-info` first and then become "" and current time (due to `format-time-string` spec) respectively, and they create a garbage entry with those values in `tabulated-list-entries`.  Can we still use `cl-loop` with avoiding this issue in a smart way??

**Comment by shingo256** [comment]
BTW, thanks to your suggestion to use `parse-iso8601-time-string', now user can customize time format displayed in the list as well as size format.  I appreciate.  Also, downloaded rubbish.py :-)

**Comment by alphapapa** [comment]
> Can we still use `cl-loop` with avoiding this issue in a smart way??

I made some adjustments, I think this will do it:
```el
(defun trashed-read-files ()
  (let* ((files (directory-files-and-attributes trashed-files-dir nil nil t))
         (entries (cl-loop for (name . attrs) in files
                           unless (or (string= name ".") (string= name ".."))
                           for entry = (trashed-file-info name attrs)
                           when entry collect entry)))
    (setf tabulated-list-entries entries)))

(defun trashed-file-info (name attrs)
  "Return list of name and vector for `tabulated-list-entries' for file NAME with ATTRS."
  (let ((info-file (expand-file-name (concat name ".trashinfo") trashed-info-dir)))
    (when (file-readable-p info-file)
      (-let* (((path deletion-ts) (trashed-trashinfo info-file))
              (type (cl-typecase (file-attribute-type attrs)
                      (string "l")
                      (null "-")
                      (t "d")))
              (size (number-to-string (file-attribute-size attrs)))
              (path (-> path url-unhex-string
                        (decode-coding-string 'utf-8 t)
                        (propertize 'mouse-face 'highlight)))
              (deletion-ts (format-time-string "%Y-%m-%d %H:%M:%S" deletion-ts)))
        (list name (vector type size deletion-ts path))))))

(defun trashed-trashinfo (trashinfo-file)
  "Return list of original file path and deletion timestamp for TRASHINFO-FILE."
  (with-temp-buffer
    (insert-file-contents trashinfo-file)
    (let* ((path (when (re-search-forward (rx bol "Path"
                                              (0+ blank) "=" (0+ blank)
                                              (group (1+ nonl))) nil t)
                   (match-string 1)))
           (deletion-ts (progn
                          (goto-char (point-min))
                          (when (re-search-forward (rx bol "DeletionDate"
                                                       (0+ blank) "=" (0+ blank)
                                                       (group (1+ nonl))) nil t)
                            (parse-iso8601-time-string (match-string 1))))))
      (list path deletion-ts))))
```

> BTW, thanks to your suggestion to use parse-iso8601-time-string, now user can customize time format displayed in the list as well as size format

Great!

> Also, downloaded rubbish.py :-)

Cool, let me know if you have any feedback on it.

**Comment by shingo256** [comment]
I applied the suggested code with some small modifications.  Sorry for my compromises which don't look perfect for you.  Anyway I appreciate your suggestion.  Thank you so much.
