### ISSUE TITLE
Some valid info files are rejected

### ISSUE THREAD

**Issue by alphapapa** [shingo256/trashed#2]
Hi,

I noticed that some valid info files are rejected.  For example, this one is skipped, apparently because of the spaces around the `=`, even though it's a valid file:

```
[Trash Info]
Path = /home/me/src/emacs/melpa/sandbox
DeletionDate = 2019-09-09T19:45:50
```
I also added a fix for this in https://github.com/shingo256/trashed/issues/1

Thanks.

**Comment by shingo256** [comment]
Fixed.  Thanks!

**Comment by shingo256** [comment]
Fixed.  Thanks.

**Comment by shingo256** [comment]
Fixed.  Thanks.

**Comment by shingo256** [comment]
Fixed.  Thanks!
