### ISSUE TITLE
Errror when there is no directory for trashcan

### ISSUE THREAD

**Issue by akirak** [shingo256/trashed#3]
Running `trashed` throws an error if I have never used the trashcan:

```
trashed-read-files: Opening directory: No such file or directory, /home/akirakomamura/.local/share/Trash/files
```

Apparently this is caused by evaluating the following expression in the function:

```
(directory-files-and-attributes trashed-files-dir nil nil t)
```

It can be prevented by putting the expression inside `(ignore-errors ...)`.

**Comment by shingo256** [comment]
Thank you for the report.  Fixed.
